version: "3.8"

services:
  app:
    build: .
    user: "1000:1000"
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=...
      - TELEGRAM_BOT_TOKEN=...
      - ALLOWED_TELEGRAM_USER_IDS=...
      - OPENAI_MODEL=gpt-4o
      - MAX_TOKENS=1200
      - HISTORY_SIZE_LIMIT=20
      - N_CHOICES=1
      - TEMPERATURE=1.0
      - PRESENCE_PENALTY=0
      - FREQUENCY_PENALTY=0
      - TELEGRAM_CHUNK_SIZE_LIMIT=4096
